### ISSUE TITLE
support gen3

### ISSUE THREAD

**Issue by bitnom** [igolaizola/vidai#3]
Make vidai able to support gen3

**Comment by igolaizola** [comment]
There is a new version compatible with Gen-3, but it is currently in private beta.
For access to the private repository, contact me via [Telegram](https://t.me/igolaizola), [Twitter](https://x.com/igolaizola), or my [contact form](https://igolaizola.com#contact).

**Comment by igolaizola** [comment]
Gen3 support has been added to the repository.

Enjoy it! 🥳
